2일전부터 대부분이 클라이언트 초점으로 코딩 진행했다.

데이터베이스를 연결하는 객체들을 

PM의 역할 : 관리감독
PL의 역할 : 프로젝트 리더,코치역할

RFP = 1차 하청업체 
대기업, 공기업 ->이 1차 하청업체에 RFP를 발송한다. RFP에는 가격,어떠한 목적인지 포함하고 하청업체는 그거에 대해서 할지 말지 , 가격에 대한것 모든것에 대해서 내부 협의를 시작한다.
-> 그리고 가격+내용에 대해서 제안서를 제출하고 어떠한식의 협의를 진행한다.

1.업무분석을 진행한다.

PM이 첫번째 회의록 및 업무분석서를 작성한다.
	db설계를 시작한다. 업무에 대해서 분석하고 또 요구사항을 확인한 후 제출한다. 테이블명세서 작성

PL한테는 스프링 세팅을 한다. 
	그 다음에 자바스크립트 라이브러리를 세팅시킨다. 

db와 라이브러리의 세팅이 끝나면 시작한다.

다시 디자이너와 준비하고, 업무일정표를 작성한다.(일 단위)

성적테이블을 만들어뒀는데 6개정도.. ㄱ우리가 무엇을 만들지 업무를 만든다.






SELECT *
FROM GRPCOMMONS_TBL G1, STUDENTS_TBL S1, COMMONS_TBL C1
WHERE S1.STU_DEPT_GRP=G1.GRP_ID
AND S1.STU_DEPT_GRP = C1.GRP_ID
AND G1.GRP_ID = 'GRP002'
AND S1.STU_ID = 'STU001'
;

SELECT *
FROM GRPCOMMONS_TBL G1, STUDENTS_TBL S1
WHERE S1.STU_DEPT_GRP=G1.GRP_ID
AND G1.GRP_ID = 'GRP002'
AND S1.STU_ID = 'STU001';



Q.홍길동01의 이름과 학과 동의 주소를 뽑아내기 

--이름 학과 
SELECT *
FROM STUDENTS_TBL T1, COMMONS_TBL T2, GRPCOMMONS_TBL T3
WHERE T1.STU_DEPT = T2.COM_ID
AND T1.STU_DEPT_GRP = T3.GRP_ID
AND T1.STU_ID = 'STU001'
AND T3.GRP_ID = 'GRP002'
;

--필드명으로 조인하지말고, ROW를 중심으로 JOIN걸기 
SELECT * FROM COMMONS_TBL T1, GRPCOMMONS_TBL T2
WHERE T1.GRP_ID = T2.GRP_ID
AND T2.GRP_ID = 'GRP002';

--이렇게 하면 학과가 하나씩만 나옴
SELECT * FROM COMMONS_TBL T1, GRPCOMMONS_TBL T2, STUDENTS_TBL T3
WHERE T1.GRP_ID = T2.GRP_ID
AND T1.GRP_ID = T3.STU_DEPT_GRP
AND T1.COM_ID = T3.STU_DEPT

AND T2.GRP_ID = 'GRP002'
AND T3.STU_ID = 'STU001';
--그다음 학생을 찾음 . 

SELECT * FROM COMMONS_TBL T1, GRPCOMMONS_TBL T2, STUDENTS_TBL T3, COMMONS_TBL T4
WHERE T1.GRP_ID = T2.GRP_ID
AND T1.GRP_ID = T3.STU_DEPT_GRP
AND T1.COM_ID = T3.STU_DEPT
AND T3.STU_ADDR_GRP = T4.GRP_ID
AND T3.STU_ADDR = T4.COM_ID
AND T2.GRP_ID = 'GRP002'
AND T3.STU_ID = 'STU001'
;
--학생이름 학과 동 주소 가져오기 

SELECT STU_ID, COUNT(*) FROM 
(
SELECT * FROM COMMONS_TBL T1,  STUDENTS_TBL T3, COMMONS_TBL T4, COMMONS_TBL T5, COMMONS_TBL T6
WHERE T1.GRP_ID = T3.STU_DEPT_GRP
AND T1.COM_ID = T3.STU_DEPT
AND T3.STU_ADDR_GRP = T4.GRP_ID
AND T3.STU_ADDR = T4.COM_ID
AND T4.PARENT_ID = T5.COM_ID AND T4.GRP_ID = T5.GRP_ID
AND T5.PARENT_ID = T6.COM_ID AND T5.GRP_ID = T6.GRP_ID
AND T1.GRP_ID = 'GRP002'
AND T3.STU_ID = 'STU001'
)
GROUP BY STU_ID
HAVING COUNT(*)>1
;




Q. 학과별 학생수를 구하여라  (학과와 학생이 복합키로 연결되어있다)
SELECT COM_VAL
FROM STUDENTS_TBL S1, GRPCOMMONS_TBL G1
WHERE S1.STU_DEPT_GRP = G1.GRP_ID;
AND S1.STU_DEPT = C1.COM_ID;


SELECT *
FROM GRPCOMMONS_TBL G1, STUDENTS_TBL S1
WHERE G1.GRP_ID=S1.STU_DEPT_GRP
;

--답.. T1과 T2는 복합키로 연결되어있다. T1이 1 T2가 N 관계 
SELECT T1.COM_ID, T1.COM_VAL, COUNT(*) FROM
(
SELECT * FROM COMMONS_TBL
WHERE GRP_ID = 'GRP002'
) T1
,
STUDENTS_TBL T2 
WHERE T2.STU_DEPT_GRP(+) = T1.GRP_ID
AND T2.STU_DEPT(+) = T1.COM_ID
GROUP BY T1.COM_ID, T1.COM_VAL
; --지금 여기는 이미 23개를 넘는다. 0을 안샌다.


SELECT * FROM COMMONS_TBL WHERE GRP_ID = 'GRP002' AND COM_LVL = 2; --총 23개인데 

--답.. T1과 T2는 복합키로 연결되어있다. T1이 1 T2가 N 관계 
SELECT * FROM
(
SELECT * FROM COMMONS_TBL
WHERE GRP_ID = 'GRP002' AND COM_LVL= 2
) T1, STUDENTS_TBL T2 
WHERE T2.STU_DEPT_GRP(+) = T1.GRP_ID
AND T2.STU_DEPT(+) = T1.COM_ID
; --4개 학과가 학생이 없다

SELECT T1.COM_ID, T1.COM_VAL, COUNT(T2.STU_ID) FROM
(
SELECT * FROM COMMONS_TBL
WHERE GRP_ID = 'GRP002' AND COM_LVL= 2
) T1, STUDENTS_TBL T2 
WHERE T2.STU_DEPT_GRP(+) = T1.GRP_ID
AND T2.STU_DEPT(+) = T1.COM_ID
GROUP BY T1.COM_ID, T1.COM_VAL
ORDER BY COUNT(T2.STU_ID) ASC
; 


--재형
Q.홍길동01의 이름과 학과 동의 주소를 뽑아내기
SELECT T2.COM_VAL, T2.COM_ID, NVL(T1.NUMBERS, 0) AS NUMBERS
FROM
(
SELECT STU_DEPT AS DEPART, COUNT(STU_ID) AS NUMBERS
FROM STUDENTS_TBL
GROUP BY STU_DEPT
) T1,
COMMONS_TBL T2
WHERE T1.DEPART(+) = T2.COM_ID
AND T2.GRP_ID = 'GRP002'
AND T2.COM_LVL = 2
;

Q. 학과별 학생수를 구하여라
SELECT T1.COM_ID, T1.COM_VAL, COUNT(*) FROM
(
SELECT * FROM COMMONS_TBL
WHERE GRP_ID = 'GRP002'
) T1
,
STUDENTS_TBL T2 
WHERE T2.STU_DEPT_GRP(+) = T1.GRP_ID
AND T2.STU_DEPT(+) = T1.COM_ID
GROUP BY T1.COM_ID, T1.COM_VAL;






